version: '3'

services:

  nodejs-skeleton:
    image: myplayground/nodejs-skeleton:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - PORT=8080
      - DB_HOST=my_db
      - DB_PORT=5432
      - DB_NAME=my_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_CONNECTION_URL=redis://redis:6379
    ports:
      - 8080
    networks:
      - dansMepro

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - dansMepro

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '55432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - dansMepro

networks:
  dansMepro:

volumes:
  tempo-data:
  loki-data:
  db: